language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

sudo: false

before_script:
    - composer self-update && composer install

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
    - travis_retry php php-coveralls.phar -e test -x build/logs/clover.xml -o build/logs/coveralls.json
